# Site settings
title: NSF CSSI PI Meeting 2020
email: rafsilva@isi.edu
description: > # this means to ignore newlines until "baseurl:"
  NSF CSSI PI Meeting 2020
#baseurl: "/2020-meeting"
#url: "https://cssi-pi-community.github.io"

# Build settings
markdown: kramdown

assets:
  sources:
    - fonts
    - images
    - assets/js
    - css

gems:
  - jekyll-assets

