# Site settings
title: NSF CSSI PI Meeting 2019
email: rafsilva@isi.edu
description: > # this means to ignore newlines until "baseurl:"
  NSF CSSI PI Meeting 2019
#baseurl: "/2019-meeting"
#url: "http://cssi-pi-community.github.io"

# Build settings
markdown: kramdown

assets:
  sources:
    - fonts
    - images
    - assets/js
    - css

gems:
  - jekyll-assets

